name: Prettier
on: [push]

jobs: 
    build: 
        name: Prettier
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@1
            - uses: bahmutov/npm-install@v1

            - run: npm run format
            - run: git status

            - uses: mikeal/publiah-to-github-action@master
              env: 
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                BRANCH_NAME: 18-ubeydullah # This will be changed